// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzmpluozxywemvxodqin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bXBsdW96eHl3ZW12eG9kcWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MDE5MjAsImV4cCI6MjA3OTk3NzkyMH0.t06w7vLEowzW8_93Vz7PxWQKs0yH3b6R91ATJAgNZJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});